version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging into Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 381492276319.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building the Docker image..."
      - docker build -t flask-app .
      - docker tag barot-repo:latest 381492276319.dkr.ecr.us-east-1.amazonaws.com/barot-repo:latest
  post_build:
    commands:
      - echo "Pushing the Docker image to ECR..."
      - docker push 381492276319.dkr.ecr.us-east-1.amazonaws.com/barot-repo:latest
      - echo "Build complete"
